cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  epsilon_init: 1
  epsilon_decay: 0.99995
  epsilon_min : 0.05
  mini_batch_size: 32
  network_sync_rate: 10
  discount_factor: 0.99
  learning_rate: 0.001
  stop_on_reward: 100000
  fc1_nodes: 128
  enable_double_dqn: False
  enable_dueling_dqn: True